### ISSUE TITLE
Descriptive info on the example data needed 

### ISSUE THREAD

**Issue by xiaohy9** [sunlabuiuc/PyHealth#12]
I found your PyHealth package a valuable resource. I am trying the test_sequence_data.ipynb notebook with example dataset. While the csv files in /datasets/mimic/y_data/ folder seems to be clear because the column names are self-explanatory, but not the ones in /datasets/mimic/x_data/ folder, which has no column names. I’ve read the readme files and online documentation, couldn’t find anything. Can you help me on this? 

BTW, it would help a lot if you could add some minimal description on the data, data processing or training steps in the notebook. That would help the users a lot, because they don’t have to spend a lot of time finding the info everywhere.

**Comment by yzhao062** [comment]
if my memory is correct...the data is generated by https://raw.githubusercontent.com/yzhao062/PyHealth/master/examples/data_generation/dataloader_mimic_demo_parallel.py 

So X includes the features below:
    var_list = ['Capillary refill rate',
                'Diastolic blood pressure',
                'Fraction inspired oxygen',
                'Glascow coma scale eye opening',
                'Glascow coma scale motor response',
                'Glascow coma scale total',
                'Glascow coma scale verbal response',
                'Glucose',
                'Heart Rate',
                'Height',
                'Mean blood pressure',
                'Oxygen saturation',
                'Respiratory rate',
                'Systolic blood pressure',
                'Temperature',
                'Weight',
                'pH']

with some transformation and conversion. Sorry, we have not maintained the project since then so the support will be limited.

**Comment by xiaohy9** [comment]
thanks for the quick response.
Features in the files are columns, rows are time points? Are these time points evenly distributed, and what’s the time intervals? Thanks.

**Comment by zzachw** [comment]
Thanks for your interest in PyHealth. We have released a brand-new version of PyHealth. It includes more EHR datasets, health-related tasks, and state-of-the-art models. Welcome to try it out!
