### ISSUE TITLE
How to use any of model for mimic-iii code prediction?

### ISSUE THREAD

**Issue by Abhinav43** [sunlabuiuc/PyHealth#13]
I am trying mimic-iii code prediction task, how I can feed data, pretrained embeddings, vocab, etc. Also, How to use models after that, a simple minimal example would be beneficial.

Thank you!

**Comment by ycq091044** [comment]
The problem is solved in the new pyhealth version. We support medical code mapping and EHR code prediction. The new version has cleaner data structures and colab tutorial demos. We will support pretrained embeddings very soon.
