### ISSUE TITLE
Hello, the question about repositorie "Pandarallel"

### ISSUE THREAD

**Issue by jiangxinke** [sunlabuiuc/PyHealth#174]
When I perform prediction tasks on the mimic-iv dataset, due to the amount of mimic-iv, my code is always in deadlock, like the before issue.

I want to know the specific version about 'pandas' and 'pandarallel', thanks!

**Comment by jiangxinke** [comment]
<img width="935" alt="image" src="https://github.com/sunlabuiuc/PyHealth/assets/3205641/70362dd9-7803-40f2-89c2-7669f17e888a">

Always in this situation.

Code is abnormal when performing "group_df.apply()" block.

**Comment by ycq091044** [comment]
Sorry for the late response. I think you may need restrict pandas to <2.0.

The following version works for me (for your refenence):
<img width="449" alt="image" src="https://github.com/sunlabuiuc/PyHealth/assets/22296469/c9b0c0cb-9279-47a7-a73f-9c5ed8a0ed47">

**Comment by jiangxinke** [comment]
thanks
