### ISSUE TITLE
API doc link seems to be broken

### ISSUE THREAD

**Issue by ZhaoxiangSimonCai** [sunlabuiuc/PyHealth#2]
https://pyhealth.readthedocs.io/en/latest/pyhealth.html

![image](https://user-images.githubusercontent.com/21287206/89478437-5279b280-d7d3-11ea-928a-dbdaa4ec2b0b.png)

**Comment by yzhao062** [comment]
Thanks for the note. the doc link is fixed :) https://pyhealth.readthedocs.io/en/latest/
