### ISSUE TITLE
question about MIMIC-III in drug recommendation task

### ISSUE THREAD

**Issue by He-Yichen** [sunlabuiuc/PyHealth#206]
The MIMIC-III dataset used in many of the papers (eg. SafeDrug, GAMENet, MoleRec) consists of 50,206 medical encounter records. By filtering out the patients with only one visit, they would contain 14,995 visits and 6,350 patients, In the code of drug_recommendation_mimic3_fn,  they appear to have the same task as in the paper, but using "mimic3_ds= mimic3_ds.set_task(task_fn=drug_recommendation_mimic3_fn)" would only produce 911 patients and 1858 Visits, why is this?

**Comment by ycq091044** [comment]
Thanks for your question. We will look into it.

**Comment by ycq091044** [comment]
Hello, I think you should use the "dev=False" mode to call the MIMIC3Dataset. Here are my screenshots:
<img width="847" alt="image" src="https://github.com/sunlabuiuc/PyHealth/assets/22296469/f2aac597-c7e9-4b6a-a34d-e4736037bbcf">

**Comment by He-Yichen** [comment]
@ycq091044 Hi，here are my screenshots. Why do I get different results than yours? Is it because the "root" parameter is different?
![image](https://github.com/sunlabuiuc/PyHealth/assets/90712879/21c2435f-b0fd-4258-bdb4-08ed0732dee3)

**Comment by ycq091044** [comment]
Ok, you are using the synthetic MIMIC-III data (which is generated by ourselves and it is not the real MIMIC-III), since we are not allowed to distribute the real MIMIC-III data and you have to request it from https://physionet.org/content/mimiciii/1.4/
