### ISSUE TITLE
wrong code in pyhealth\metrics\drug_recommendation.py

### ISSUE THREAD

**Issue by Tyunsen** [sunlabuiuc/PyHealth#249]
Hello, when you update the code, you wrote the wrong code to calculate ddi, the original code is correct. It bothered me all morning. ^ ^

if ddi_matrix[i, j] == 1 or ddi_matrix[j, i] == 1: # wrong code
if ddi_matrix[med_i, med_j] == 1 or ddi_matrix[med_j, med_i] == 1: # Old and correct code

**Comment by ycq091044** [comment]
Thanks very much @Tyunsen ! Sorry for the error.

We made a mistake when integrating the ddi metric into multilabel metric func. Right now, the problem is fixed. Sorry to cause trouble for your code!
