### ISSUE TITLE
pip install version

### ISSUE THREAD

**Issue by Data-Designer** [sunlabuiuc/PyHealth#252]
Hello, I recently installed PyHealth using the command ```pip install pyhealth''', and it installed version 1.1.4. However, I noticed some discrepancies between this version and the latest code available on GitHub. For example, the multilabel_metrics_fn seems to be different.

**Comment by ycq091044** [comment]
Y, there are some new developments going on. To use the lastest version, please directly install from the github. We will upload a new version to PyPI soon.
