### ISSUE TITLE
Getting error while loading OMOP dataset 

### ISSUE THREAD

**Issue by V2dha** [sunlabuiuc/PyHealth#257]
While loading the OMOP dataset I am getting the following error. 
<img width="804" alt="image" src="https://github.com/sunlabuiuc/PyHealth/assets/50369708/de734a67-69cc-40eb-95fa-9bee6168adbd">

**Comment by pat-jj** [comment]
Please change "root" to 
`https://storage.googleapis.com/pyhealth/synpuf1k_omop_cdm_5.2.2`

**Comment by Data-Designer** [comment]
> While loading the OMOP dataset I am getting the following error. <img alt="image" width="804" src="https://private-user-images.githubusercontent.com/50369708/295828085-de734a67-69cc-40eb-95fa-9bee6168adbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTMyMTYsIm5iZiI6MTcxMzQxMjkxNiwicGF0aCI6Ii81MDM2OTcwOC8yOTU4MjgwODUtZGU3MzRhNjctNjljYy00MGViLTk1ZmEtOWJlZTYxNjhhZGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA0MDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYjY0NzFjYTFlNWY4NmFlM2RmMzhlMjBmOWY0YTI5ZGM2YzE4ODg4NmRjZTJmNGMxZmY3NWE3ZTYzYWIxZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JqniDpAYFb73FEE4IFupQRL8X6sO3ZNZC7zbc2WTrVE">

Have you solved the problem?
