### ISSUE TITLE
Bug in SafeDrug

### ISSUE THREAD

**Issue by CodeNinjaja** [sunlabuiuc/PyHealth#259]
The program crashes when I run the SafeDrug for drug recommendation with the real MIMIC-III dataset.  When I looked into the source code, I found the bug occurred in the function `generate_molecule_info()`, specifically, `adjacency = Chem.GetAdjacencyMatrix(mol)`. https://github.com/sunlabuiuc/PyHealth/blob/5592d437abf6a06df7d41204cf56971f45e98a47/pyhealth/models/safedrug.py#L529C20-L529C20

I don't know what happened. Please provide some suggestions. Thank you.
I provide a bug case here: `smile = '[F-].[Na+]'`

**Comment by ycq091044** [comment]
Sorry, it seems the function works on my end. What is your rdkit version?

<img width="650" alt="image" src="https://github.com/sunlabuiuc/PyHealth/assets/22296469/fe8d71aa-3ead-40ad-9160-78d7a55e273d">

**Comment by CodeNinjaja** [comment]
My rdkit version is 2022.9.5.  This may be due to the rdkit version,  I will try another version. Thanks for your reply! 🙏

**Comment by CodeNinjaja** [comment]
> Sorry, it seems the function works on my end. What is your rdkit version?
> 
> <img alt="image" width="650" src="https://private-user-images.githubusercontent.com/22296469/297946492-fe8d71aa-3ead-40ad-9160-78d7a55e273d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODQzNjksIm5iZiI6MTcwNTY4NDA2OSwicGF0aCI6Ii8yMjI5NjQ2OS8yOTc5NDY0OTItZmU4ZDcxYWEtM2VhZC00MGFkLTkxNjAtNzhkN2E1NWUyNzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE3MDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYjc5MGYxY2IzZDU4YjY1YjI5MTEzMzllMGEyYWRhZGM2MmM0MmI3ZWJlN2I5N2JkMTE2OTIyOGI1NmVmYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p9mnbnsUmGfw-HuUaEfDs5O3f9y4UzXojpMhSxE081U">

My rdkit version is 2022.9.5. This may be due to the rdkit version, I will try another version. Thanks for your reply! 🙏
