### ISSUE TITLE
ImportError: cannot import name 'MIMIC3BaseDataset' from 'pyhealth.datasets' 

### ISSUE THREAD

**Issue by ChandlerBang** [sunlabuiuc/PyHealth#276]
Hi,

When I was testing the example in https://pyhealth.readthedocs.io/en/latest/examples_bak.html#step-3-build-deep-learning-models, I found I could not load the dataset. Could you help look into this issue? Thank you!

```
> python test_retain.py
Traceback (most recent call last):
  File "test_retain.py", line 1, in <module>
    from pyhealth.datasets import MIMIC3BaseDataset
ImportError: cannot import name 'MIMIC3BaseDataset' from 'pyhealth.datasets' (/Users/anaconda3/envs/ehr/lib/python3.8/site-packages/pyhealth/datasets/__init__.py)
```

I also tried to search the class `MIMIC3BaseDataset` over this repo but could not find it. Any help would be appreciated!

**Comment by ycq091044** [comment]
Hi,

Sorry for the late reply. The page you are referring to is a deprecated page which uses the fairly old version. Please follow this page for the new example https://pyhealth.readthedocs.io/en/latest/.

We have "MIMIC3Dataset" module not the "MIMIC3BaseDataset".

Thanks,
Chaoqi
