### ISSUE TITLE
RxNorm codes hierarchy

### ISSUE THREAD

**Issue by Ofir408** [sunlabuiuc/PyHealth#277]
Hi, I noticed something that might seem strange in the hierarchy of `RxNorm` (and perhaps other vocabularies). 
For instance, the code `1000001` in `RxNorm` doesn't have any parents or children in the `PyHealth` hierarchy.

![image](https://github.com/sunlabuiuc/PyHealth/assets/33639234/25574aeb-80c3-4260-9544-123c4ccc03ba)
However, according Athena it looks this code has parents and children: 
![image](https://github.com/sunlabuiuc/PyHealth/assets/33639234/d00f0c62-416a-40b5-9d1c-2930c6fe3ae0)

This isn't specific to this code alone; it applies to many others as well. I just used 1000001 as an example.
I would like to use PyHealth for getting the hierarchy of `RxNorm` . 
Can you please check this? How can I get the hierarchy of `RxNorm` correctly?
Thank you!
@pat-jj

**Comment by zzachw** [comment]
Hi @Ofir408, sorry for the late response! PyHealth currently does not provide any relationship information between RxNorm codes. However, you can map RxNorm to ATC and use the ATC hierarchy provided in PyHealth. Thanks!
