### ISSUE TITLE
DDI of eICU dataset and omop dataset

### ISSUE THREAD

**Issue by Data-Designer** [sunlabuiuc/PyHealth#280]
Hi. Can we use pyhealth to caculate DDI rate in these two dataset?

**Comment by Data-Designer** [comment]
Additionally, drugrec function for OMOP dataset doesn't work.

```python 
from pyhealth.datasets import OMOPDataset
omop_base = OMOPDataset(
    root="https://storage.googleapis.com/pyhealth/synpuf1k_omop_cdm_5.2.2",
    tables=["condition_occurrence", "procedure_occurrence"],
    code_mapping={},
)
from pyhealth.tasks import drug_recommendation_omop_fn
omop_sample = omop_base.set_task(drug_recommendation_eicu_fn)

**Comment by ycq091044** [comment]
Sorry, we do not support DDI calculation in OMOP.

The current DDI calculation is based on ATC-3. If you could manually map OMOP drug codes to ATC-3, then it is possible to calculate the DDI score.
