### ISSUE TITLE
drugrec for OMOP datasets doesn't work

### ISSUE THREAD

**Issue by Data-Designer** [sunlabuiuc/PyHealth#282]
```python 
from pyhealth.datasets import OMOPDataset
omop_base = OMOPDataset(
    root="https://storage.googleapis.com/pyhealth/synpuf1k_omop_cdm_5.2.2",
    tables=["condition_occurrence", "procedure_occurrence"],
    code_mapping={},
)
from pyhealth.tasks import drug_recommendation_omop_fn
omop_sample = omop_base.set_task(drug_recommendation_eicu_fn)

**Comment by ycq091044** [comment]
Thanks for the question @Data-Designer . What was the error that you got?

If you have this error:

`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>`

Please add the following command before the Dataset API:

```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by Data-Designer** [comment]
> Thanks for the question @Data-Designer . What was the error that you got?
> 
> If you have this error:
> 
> `urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>`
> 
> Please add the following command before the Dataset API:
> 
> ```
> import ssl
> ssl._create_default_https_context = ssl._create_unverified_context
> ```
```python
from pyhealth.datasets import OMOPDataset
omop_base = OMOPDataset(
    root="https://storage.googleapis.com/pyhealth/synpuf1k_omop_cdm_5.2.2",
    tables=["condition_occurrence", "procedure_occurrence"],
    code_mapping={},
)
print(omop_base.patients)
```
I got the output like this.

{'1': Patient 1 with 7 visits, '10': Patient 10 with 3 visits, '100': Patient 100 with 47 visits, '1000': Patient 1000 with 58 visits, '1001': Patient 1001 with 12 visits, '1002': Patient 1002 with 111 visits, '1003': Patient 1003 with 5 visits, '1004': Patient 1004 with 54 visits, '1005': Patient 1005 with 26 visits}

Then, when i run 
```python
from pyhealth.tasks import drug_recommendation_omop_fn
omop_sample = omop_base.set_task(drug_recommendation_eicu_fn)
```

It is wrong, 
<img width="612" alt="image" src="https://github.com/sunlabuiuc/PyHealth/assets/72868569/f4699369-619a-41c3-876a-3279fbe65c6e">

**Comment by Data-Designer** [comment]
Statistics of base dataset (dev=False):
	- Dataset: OMOPDataset
	- Number of patients: 1000
	- Number of visits: 55261
	- Number of visits per patient: 55.2610
	- Number of events per visit in condition_occurrence: 0.0000
	- Number of events per visit in procedure_occurrence: 2.4886
	- Number of events per visit in drug_exposure: 0.1387
	
	
This error may come from the zero condition_occurrence?

**Comment by ycq091044** [comment]
Thanks @Data-Designer for your question!

I do find a minor bug in the code and have filed a PR #287 (a very simple fix). Right now it should be fixed. Please check.

Thanks again.
