### ISSUE TITLE
Is it possible to support ICD11 InnerMap?

### ISSUE THREAD

**Issue by Ofir408** [sunlabuiuc/PyHealth#297]
Hi, 
ICD-11 has become very common in recent years, but I see that PyHealth only supports ICD-9 and ICD-10 with `InnerMap`. Is it possible to add support for ICD-11 as well?

For example: 
```
from pyhealth.medcode import InnerMap

InnerMap.load("ICD11CM") 
InnerMap.load("ICD11PROC") 

```
Thank you very much.

**Comment by zzachw** [comment]
Thanks for the suggestion! We will add this to our PR list.

**Comment by Ofir408** [comment]
@zzachw  Do you have an estimate for when this feature will be available? I wanted to use it with pyhealth for research I'm doing. Thanks!
