### ISSUE TITLE
How-to-contribute section is still missing

### ISSUE THREAD

**Issue by ZhaoxiangSimonCai** [sunlabuiuc/PyHealth#3]
https://github.com/yzhao062/PyHealth#how-to-contribute

too keen on contributing 😂

**Comment by yzhao062** [comment]
Hey Simon. Thanks for reaching out. It is currently at a very early stage. If you are interested in contributing, we may discuss offline for something. Or you are welcome to check back a few days or weeks later for "help wanted" in under issues. thanks for the interest again.

**Comment by ZhaoxiangSimonCai** [comment]
> Hey Simon. Thanks for reaching out. It is currently at a very early stage. If you are interested in contributing, we may discuss offline for something. Or you are welcome to check back a few days or weeks later for "help wanted" in under issues. thanks for the interest again.

Hey Yue, that sounds exciting! Let me spend some time playing with it first and then we can chat about how I could help. What's the best way to discuss this with you? Email or wechat? BTW thanks for adding on LinkedIn :D
