### ISSUE TITLE
sequential_drug_recommendation

### ISSUE THREAD

**Issue by bbb801** [sunlabuiuc/PyHealth#55]
Dear sir/Madam,

In 'Advanced Case 2: Work on customized healthcare task' , I have questions about 'sequential_drugs' and 'drugs'  (see following codes). It seems 'sequential_drugs' is always empty. What ' sequential_drugs[-1] = drugs' is used for at the final row?

def sequential_drug_recommendation(patient):
    samples = []

    sequential_conditions = []
    sequential_procedures = []
    sequential_drugs = [] # not include the drugs now
    for visit in patient:

        # step 1: obtain feature information
        conditions = visit.get_code_list(table="DIAGNOSES_ICD")
        procedures = visit.get_code_list(table="PROCEDURES_ICD")
        drugs = visit.get_code_list(table="PRESCRIPTIONS")

        sequential_conditions.append(conditions)
        sequential_procedures.append(drugs)
        sequential_drugs.append([])

        # step 2: exclusion criteria: visits without drug
        if len(drugs) == 0: 
            sequential_drugs[-1] = drugs
            continue

        # step 3: assemble the samples
        samples.append(
            {
                "visit_id": visit.visit_id,
                "patient_id": patient.patient_id,
                # the following keys can be the "feature_keys" or "label_key" for initializing downstream ML model
                "sequential_conditions": sequential_drugs.copy(),
                "sequential_procedures": sequential_procedures.copy(),
                "sequential_drugs": sequential_drugs.copy(),
                "label": drugs,
            }
        )
        sequential_drugs[-1] = drugs

    return samples

**Comment by ycq091044** [comment]
Thanks for the question. `sequential_drug_recommendation` works as an example to show how to define a healthcare task in pyhealth.  By definition: 
> Sequential drug recommendation aims at predicting the drug set of the current visit given the history of diagnosis and procedure information as well as past drug information.

We want to use `the diagnosis and procedures of visit-1 up to visit-N` and `the drug information from visit-1 up to visit-(N-1)` to predict `the drug in visit-N`. A sample in this task looks like this:
```python
{
   "patient_id": xxx,
   "visit_id": xxx,
   "sequential_conditions": [diagnoses-visit-1, diagnosis-visit-2, ..., diagnosis-visit-N],
   "sequential_procedures": [procedure-visit-1, procedure-visit-2, ..., procedure-visit-N],
   "sequential_drugs": [drug-visit-1, drug-visit-2, ..., drug-visit-(N-1)],
   "label": [drug-visit-N],
}
```

Some explanations for the task:
1. The current drugs are what we want to predict, so they cannot be included in the feature lists. Thus, we use
```python
sequential_conditions.append(conditions)
sequential_procedures.append(drugs)
sequential_drugs.append([])
```

2. If the current drugs (i.e., predicted targets are empty, we ignore this visit).
```python
if len(drugs) == 0: 
    sequential_drugs[-1] = drugs
    continue
```

3. After we obtain the sample for the current visit, we will have to add the drugs back for the next visit. Thus we have the following line in the end.
```python
sequential_drugs[-1] = drugs
```

4. For the question "It seems 'sequential_drugs' is always empty." Because many patients only have one visit.

**Comment by bbb801** [comment]
Thank you very much.
________________________________
From: Chaoqi Yang ***@***.***>
Sent: Thursday, 29 December 2022 03:54
To: sunlabuiuc/PyHealth ***@***.***>
Cc: Dr. LIU Jundong ***@***.***>; Author ***@***.***>
Subject: [Ext] Re: [sunlabuiuc/PyHealth] sequential_drug_recommendation (Issue #55)

This email originated from outside of City University of Hong Kong. Do not reply, click links, or open attachments unless you confirm the identity of the sender and know that the content is safe.


Thanks for the question. sequential_drug_recommendation works as an example to show how to define a healthcare task in pyhealth. By definition:

Sequential drug recommendation aims at predicting the drug set of the current visit given the history of diagnosis and procedure information as well as past drug information.

We want to use the diagnosis and procedures of visit-1 up to visit-N and the drug information from visit-1 up to visit-(N-1) to predict the drug in visit-N. A sample in this task looks like this:

{
   "patient_id": xxx,
   "visit_id": xxx,
   "sequential_conditions": [diagnoses-visit-1, diagnosis-visit-2, ..., diagnosis-visit-N],
   "sequential_procedures": [procedure-visit-1, procedure-visit-2, ..., procedure-visit-N],
   "sequential_drugs": [drug-visit-1, drug-visit-2, ..., drug-visit-(N-1)],
   "label": [drug-visit-N],
}

Some explanations for the task:

  1.  The current drugs are what we want to predict, so they cannot be included in the feature lists. Thus, we use

sequential_conditions.append(conditions)
sequential_procedures.append(drugs)
sequential_drugs.append([])

  1.  If the current drugs (i.e., predicted targets are empty, we ignore this visit).

if len(drugs) == 0:
    sequential_drugs[-1] = drugs
    continue

  1.  After we obtain the sample for the current visit, we will have to add the drugs back for the next visit. Thus we have the following line in the end.

sequential_drugs[-1] = drugs

  1.  For the question "It seems 'sequential_drugs' is always empty." Because many patients only have one visit.

**Comment by bbb801** [comment]
Thank you. I still have a question about the following codes. May I know why 'drug' is in 'sequential_procedures.append(drugs)' instead of ' procedures'?

"""
Some explanations for the task:

The current drugs are what we want to predict, so they cannot be included in the feature lists. Thus, we use
sequential_conditions.append(conditions)
sequential_procedures.append(drugs)
sequential_drugs.append([])
"""

**Comment by ycq091044** [comment]
Good findings. This is a typo, just corrected.
