### ISSUE TITLE
How to generate x_data as the data in datasets?

### ISSUE THREAD

**Issue by JasonJYang** [sunlabuiuc/PyHealth#8]
Hi, thanks for your great work! I am trying to run your code using the mimic-iii-demo dataset. The problem I met is that I don't know how to generate the x_data as the data in datasets (mimic or cms). I followed your instructions but only got the y_data after running generate_mortality_prediction_mimic_demo.py. Is this because the data in the datasets folder used the full variables of mimic-iii data while only a few of them existed in mimic-iii-demo data? Thanks!

**Comment by mole-bai** [comment]
I also encountered the same problem, how do you solve it?

**Comment by ycq091044** [comment]
The problem is solved in the new pyhealth version. The new version has cleaner data structures and colab tutorial demos.
